//
// Created by Asus on 06.05.2023.
//

#ifndef CHESS_BOARD_H
#define CHESS_BOARD_H

#define ROWS_OF_BOARD 8
#define COLUMNS_OF_BOARD 8

#define PAWNS_ROW 7
#define KING_POSITION E1
#define QUEEN_POSITION D1
#define FIRST_ROOK_POSITION "A1"
#define SECOND_ROOK_POSITION H1
#define FIRST_BISHOP_POSITION C1
#define SECOND_BISHOP_POSITION F1
#define FIRST_KNIGHT_POSITION B1
#define SECOND_KNIGHT_POSITION G1

#define ENEMY_PAWNS_ROW 2
#define ENEMY_FIRST_BISHOP_POSITION C8
#define ENEMY_SECOND_BISHOP_POSITION F8
#define ENEMY_FIRST_KNIGHT_POSITION B8
#define ENEMY_SECOND_KNIGHT_POSITION G8
#define ENEMY_FIRST_ROOK_POSITION A8
#define ENEMY_SECOND_ROOK_POSITION H8
#define ENEMY_QUEEN_POSITION D8
#define ENEMY_POSITION E1

class Board {
private:
    int chess_board[ROWS_OF_BOARD][COLUMNS_OF_BOARD];


public:
    Board();
};


#endif //CHESS_BOARD_H
